In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
number_board[0].shape

(40,)

In [71]:
class Notations:


    ONE = np.zeros(shape=(80,40))
    ONE[10:70, 18:22] = 255


    TWO = np.zeros(shape=(10,10))
    TWO[4:6] = 255


    THREE = np.zeros(shape=(10,10))
    _mask = np.abs(np.add.outer(np.arange(10), -np.arange(10))) < 2
    THREE[_mask] = 255

    FOUR = np.rot90(THREE)

    _line = np.zeros(shape=(10,10))
    _line[:2] = 255
    FIVE = FOUR + _line

    SIX = np.zeros(shape=(10,10))
    SIX[:,8:] = 255

    SEVEN = SIX + _line

    _bottom_line = np.zeros(shape=(10,10))
    _bottom_line[8:] = 255
    EIGHT = SIX + _bottom_line

    NINE = EIGHT + _line

class Number:

    def __init__(self):
        self.number = Notations.ONE

    def show_number(self):
        plt.imshow(self.number)
        plt.show()

    def set_number(self, n):
        pass


    def save_number(self):
        pass

# n = Number()
# n.set_number(1)
# n.show_number()

In [73]:
Notations.NINE

array([[255., 255., 255., 255., 255., 255., 255., 255., 510., 510.],
       [255., 255., 255., 255., 255., 255., 255., 255., 510., 510.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 510., 510.],
       [255., 255., 255., 255., 255., 255., 255., 255., 510., 510.]])

In [61]:
Notations.FOUR

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 255., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0., 255., 255., 255.,   0.],
       [  0.,   0.,   0.,   0.,   0., 255., 255., 255.,   0.,   0.],
       [  0.,   0.,   0.,   0., 255., 255., 255.,   0.,   0.,   0.],
       [  0.,   0.,   0., 255., 255., 255.,   0.,   0.,   0.,   0.],
       [  0.,   0., 255., 255., 255.,   0.,   0.,   0.,   0.,   0.],
       [  0., 255., 255., 255.,   0.,   0.,   0.,   0.,   0.,   0.],
       [255., 255., 255.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [255., 255.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [55]:
Notations.TWO

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])